package com.pagos.Pojos;
// Generated 1/05/2017 01:09:13 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Abonos generated by hbm2java
 */
public class Abonos  implements java.io.Serializable {


     private Integer idabonos;
     private Cliente cliente;
     private Empleado empleado;
     private Ruta ruta;
     private Long precioTotal;
     private Long saldofinal;
     private Date fecharegistro;
     private Date fechaPlazo;
     private String estado;
     private Integer cuota;
     private Integer totalCuotas;
     private Long valorCuota;
     private Integer cuotaVencida;
     private Set abonosecundarios = new HashSet(0);

    public Abonos() {
    }

	
    public Abonos(Cliente cliente, Empleado empleado) {
        this.cliente = cliente;
        this.empleado = empleado;
    }
    public Abonos(Cliente cliente, Empleado empleado, Ruta ruta, Long precioTotal, Long saldofinal, Date fecharegistro, Date fechaPlazo, String estado, Integer cuota, Integer totalCuotas, Long valorCuota, Integer cuotaVencida, Set abonosecundarios) {
       this.cliente = cliente;
       this.empleado = empleado;
       this.ruta = ruta;
       this.precioTotal = precioTotal;
       this.saldofinal = saldofinal;
       this.fecharegistro = fecharegistro;
       this.fechaPlazo = fechaPlazo;
       this.estado = estado;
       this.cuota = cuota;
       this.totalCuotas = totalCuotas;
       this.valorCuota = valorCuota;
       this.cuotaVencida = cuotaVencida;
       this.abonosecundarios = abonosecundarios;
    }
   
    public Integer getIdabonos() {
        return this.idabonos;
    }
    
    public void setIdabonos(Integer idabonos) {
        this.idabonos = idabonos;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public Empleado getEmpleado() {
        return this.empleado;
    }
    
    public void setEmpleado(Empleado empleado) {
        this.empleado = empleado;
    }
    public Ruta getRuta() {
        return this.ruta;
    }
    
    public void setRuta(Ruta ruta) {
        this.ruta = ruta;
    }
    public Long getPrecioTotal() {
        return this.precioTotal;
    }
    
    public void setPrecioTotal(Long precioTotal) {
        this.precioTotal = precioTotal;
    }
    public Long getSaldofinal() {
        return this.saldofinal;
    }
    
    public void setSaldofinal(Long saldofinal) {
        this.saldofinal = saldofinal;
    }
    public Date getFecharegistro() {
        return this.fecharegistro;
    }
    
    public void setFecharegistro(Date fecharegistro) {
        this.fecharegistro = fecharegistro;
    }
    public Date getFechaPlazo() {
        return this.fechaPlazo;
    }
    
    public void setFechaPlazo(Date fechaPlazo) {
        this.fechaPlazo = fechaPlazo;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Integer getCuota() {
        return this.cuota;
    }
    
    public void setCuota(Integer cuota) {
        this.cuota = cuota;
    }
    public Integer getTotalCuotas() {
        return this.totalCuotas;
    }
    
    public void setTotalCuotas(Integer totalCuotas) {
        this.totalCuotas = totalCuotas;
    }
    public Long getValorCuota() {
        return this.valorCuota;
    }
    
    public void setValorCuota(Long valorCuota) {
        this.valorCuota = valorCuota;
    }
    public Integer getCuotaVencida() {
        return this.cuotaVencida;
    }
    
    public void setCuotaVencida(Integer cuotaVencida) {
        this.cuotaVencida = cuotaVencida;
    }
    public Set getAbonosecundarios() {
        return this.abonosecundarios;
    }
    
    public void setAbonosecundarios(Set abonosecundarios) {
        this.abonosecundarios = abonosecundarios;
    }




}


