package com.pagos.Pojos;
// Generated 8/05/2017 04:50:17 PM by Hibernate Tools 4.3.1



/**
 * Ciudad generated by hbm2java
 */
public class Ciudad  implements java.io.Serializable {


     private int idciudad;
     private String nombreCiu;

    public Ciudad() {
    }

    public Ciudad(int idciudad, String nombreCiu) {
       this.idciudad = idciudad;
       this.nombreCiu = nombreCiu;
    }
   
    public int getIdciudad() {
        return this.idciudad;
    }
    
    public void setIdciudad(int idciudad) {
        this.idciudad = idciudad;
    }
    public String getNombreCiu() {
        return this.nombreCiu;
    }
    
    public void setNombreCiu(String nombreCiu) {
        this.nombreCiu = nombreCiu;
    }




}


