package com.pagos.Pojos;
// Generated 8/05/2017 04:50:17 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Cliente generated by hbm2java
 */
public class Cliente  implements java.io.Serializable {


     private Integer idcliente;
     private String nombre;
     private String apellidos;
     private String numeroDocumentoC;
     private String telefono;
     private String direccion;
     private Date fechaRegistro;
     private String ocupacion;
     private String codigo;
     private Set abonoses = new HashSet(0);

    public Cliente() {
    }

	
    public Cliente(String nombre, String numeroDocumentoC) {
        this.nombre = nombre;
        this.numeroDocumentoC = numeroDocumentoC;
    }
    public Cliente(String nombre, String apellidos, String numeroDocumentoC, String telefono, String direccion, Date fechaRegistro, String ocupacion, String codigo, Set abonoses) {
       this.nombre = nombre;
       this.apellidos = apellidos;
       this.numeroDocumentoC = numeroDocumentoC;
       this.telefono = telefono;
       this.direccion = direccion;
       this.fechaRegistro = fechaRegistro;
       this.ocupacion = ocupacion;
       this.codigo = codigo;
       this.abonoses = abonoses;
    }
   
    public Integer getIdcliente() {
        return this.idcliente;
    }
    
    public void setIdcliente(Integer idcliente) {
        this.idcliente = idcliente;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    public String getNumeroDocumentoC() {
        return this.numeroDocumentoC;
    }
    
    public void setNumeroDocumentoC(String numeroDocumentoC) {
        this.numeroDocumentoC = numeroDocumentoC;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }
    
    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }
    public String getOcupacion() {
        return this.ocupacion;
    }
    
    public void setOcupacion(String ocupacion) {
        this.ocupacion = ocupacion;
    }
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }
    public Set getAbonoses() {
        return this.abonoses;
    }
    
    public void setAbonoses(Set abonoses) {
        this.abonoses = abonoses;
    }




}


