package com.pagos.Pojos;
// Generated 8/05/2017 04:50:17 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Empleado generated by hbm2java
 */
public class Empleado  implements java.io.Serializable {


     private Integer idempleado;
     private Rol rol;
     private Tipodocumento tipodocumento;
     private String numeroDocumento;
     private String nombre;
     private String apellidos;
     private String correoElectronico;
     private String password;
     private String telefono;
     private String direccion;
     private Set cajas = new HashSet(0);
     private Set abonosecundarios = new HashSet(0);
     private Set abonoses = new HashSet(0);
     private Set gastos = new HashSet(0);

    public Empleado() {
    }

	
    public Empleado(Rol rol, String numeroDocumento, String nombre, String apellidos, String correoElectronico) {
        this.rol = rol;
        this.numeroDocumento = numeroDocumento;
        this.nombre = nombre;
        this.apellidos = apellidos;
        this.correoElectronico = correoElectronico;
    }
    public Empleado(Rol rol, Tipodocumento tipodocumento, String numeroDocumento, String nombre, String apellidos, String correoElectronico, String password, String telefono, String direccion, Set cajas, Set abonosecundarios, Set abonoses, Set gastos) {
       this.rol = rol;
       this.tipodocumento = tipodocumento;
       this.numeroDocumento = numeroDocumento;
       this.nombre = nombre;
       this.apellidos = apellidos;
       this.correoElectronico = correoElectronico;
       this.password = password;
       this.telefono = telefono;
       this.direccion = direccion;
       this.cajas = cajas;
       this.abonosecundarios = abonosecundarios;
       this.abonoses = abonoses;
       this.gastos = gastos;
    }
   
    public Integer getIdempleado() {
        return this.idempleado;
    }
    
    public void setIdempleado(Integer idempleado) {
        this.idempleado = idempleado;
    }
    public Rol getRol() {
        return this.rol;
    }
    
    public void setRol(Rol rol) {
        this.rol = rol;
    }
    public Tipodocumento getTipodocumento() {
        return this.tipodocumento;
    }
    
    public void setTipodocumento(Tipodocumento tipodocumento) {
        this.tipodocumento = tipodocumento;
    }
    public String getNumeroDocumento() {
        return this.numeroDocumento;
    }
    
    public void setNumeroDocumento(String numeroDocumento) {
        this.numeroDocumento = numeroDocumento;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    public String getCorreoElectronico() {
        return this.correoElectronico;
    }
    
    public void setCorreoElectronico(String correoElectronico) {
        this.correoElectronico = correoElectronico;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public Set getCajas() {
        return this.cajas;
    }
    
    public void setCajas(Set cajas) {
        this.cajas = cajas;
    }
    public Set getAbonosecundarios() {
        return this.abonosecundarios;
    }
    
    public void setAbonosecundarios(Set abonosecundarios) {
        this.abonosecundarios = abonosecundarios;
    }
    public Set getAbonoses() {
        return this.abonoses;
    }
    
    public void setAbonoses(Set abonoses) {
        this.abonoses = abonoses;
    }
    public Set getGastos() {
        return this.gastos;
    }
    
    public void setGastos(Set gastos) {
        this.gastos = gastos;
    }




}


