package com.pagos.Pojos;
// Generated 1/05/2017 01:09:13 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Gasto generated by hbm2java
 */
public class Gasto  implements java.io.Serializable {


     private Integer idgasto;
     private Empleado empleado;
     private Integer importe;
     private String proveedor;
     private String nombre;
     private long valor;
     private Date fecha;

    public Gasto() {
    }

	
    public Gasto(Empleado empleado, String nombre, long valor) {
        this.empleado = empleado;
        this.nombre = nombre;
        this.valor = valor;
    }
    public Gasto(Empleado empleado, Integer importe, String proveedor, String nombre, long valor, Date fecha) {
       this.empleado = empleado;
       this.importe = importe;
       this.proveedor = proveedor;
       this.nombre = nombre;
       this.valor = valor;
       this.fecha = fecha;
    }
   
    public Integer getIdgasto() {
        return this.idgasto;
    }
    
    public void setIdgasto(Integer idgasto) {
        this.idgasto = idgasto;
    }
    public Empleado getEmpleado() {
        return this.empleado;
    }
    
    public void setEmpleado(Empleado empleado) {
        this.empleado = empleado;
    }
    public Integer getImporte() {
        return this.importe;
    }
    
    public void setImporte(Integer importe) {
        this.importe = importe;
    }
    public String getProveedor() {
        return this.proveedor;
    }
    
    public void setProveedor(String proveedor) {
        this.proveedor = proveedor;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public long getValor() {
        return this.valor;
    }
    
    public void setValor(long valor) {
        this.valor = valor;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }




}


