package com.pagos.Pojos;
// Generated 8/05/2017 04:50:17 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Ruta generated by hbm2java
 */
public class Ruta  implements java.io.Serializable {


     private Integer idruta;
     private String nonbre;
     private Set abonoses = new HashSet(0);

    public Ruta() {
    }

    public Ruta(String nonbre, Set abonoses) {
       this.nonbre = nonbre;
       this.abonoses = abonoses;
    }
   
    public Integer getIdruta() {
        return this.idruta;
    }
    
    public void setIdruta(Integer idruta) {
        this.idruta = idruta;
    }
    public String getNonbre() {
        return this.nonbre;
    }
    
    public void setNonbre(String nonbre) {
        this.nonbre = nonbre;
    }
    public Set getAbonoses() {
        return this.abonoses;
    }
    
    public void setAbonoses(Set abonoses) {
        this.abonoses = abonoses;
    }




}


